[package]
name = "actix-message-example"
version = "0.1.0"
authors = ["Voronwe Sul <voronwe.s@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix = "0.10"
